# Generated by Django 6.1.2 on 2026-10-09 07:49

import django.db.models.functions.text
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('expense', 'Expense'), ('income', 'Income')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('expense', 'Expense'), ('income', 'Income')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('kind'), name='accounts_account_name_kind_ci_unique'), models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('asset', 'liability')), ('opening_balance__isnull', False), ('opening_balance_date__isnull', False)), models.Q(models.Q(('kind__in', ('asset', 'liability')), _negated=True), ('opening_balance__isnull', True), ('opening_balance_date__isnull', True)), _connector='OR'), name='accounts_account_opening_balance_by_kind', violation_error_message='Only Asset and Liability Accounts have an Opening Balance and date, and they need both.')],
            },
        ),
    ]
