# Generated by Django 6.1.2 on 2026-10-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('asset', 'liability')), ('opening_balance__isnull', False), ('opening_balance_date__isnull', False)), models.Q(models.Q(('kind__in', ('asset', 'liability')), _negated=True), ('opening_balance__isnull', True), ('opening_balance_date__isnull', True)), _connector='OR'), name='accounts_account_opening_balance_by_kind', violation_error_message='Only Asset and Liability Accounts have an Opening Balance and date, and they need both.'),
        ),
    ]
