# Generated by Django 6.1.2 on 2026-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_in_net_worth',
            field=models.BooleanField(default=True, verbose_name='Include in Net Worth'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='include_in_net_worth',
            field=models.BooleanField(default=True, verbose_name='Include in Net Worth'),
        ),
    ]
