# Generated by Django 6.1.2 on 2026-10-10 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_include_in_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The day of the month the Statement Amount must be paid by.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Due Day'),
        ),
        migrations.AddField(
            model_name='account',
            name='pays_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards_paid', to='accounts.account', verbose_name='Pays from'),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The day of the month the card's billing period closes.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Statement Day'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The day of the month the Statement Amount must be paid by.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Due Day'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='pays_from',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'kind': 'asset'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='Pays from'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='statement_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The day of the month the card's billing period closes.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Statement Day'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_day__isnull', False), ('kind', 'liability'), ('pays_from__isnull', False), ('statement_day__isnull', False)), models.Q(('due_day__isnull', True), ('pays_from__isnull', True), ('statement_day__isnull', True)), _connector='OR'), name='accounts_account_card_settings_together', violation_error_message='Set the Statement Day, Due Day and Pays from Account together, or leave all three blank.'),
        ),
    ]
