# Generated by Django 6.1.2 on 2026-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_card_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Warn when the Forecast expects the Balance to fall below this.', max_digits=15, verbose_name='Low-Balance Threshold'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Warn when the Forecast expects the Balance to fall below this.', max_digits=15, verbose_name='Low-Balance Threshold'),
        ),
    ]
