default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "0.26"
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.12.23"
    hooks:
      - id: uv-lock

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.33.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "6.1"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.51.1
    hooks:
      - id: typos

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
