# Generated by Django 6.1.2 on 2026-10-09 17:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_include_in_net_worth'),
        ('classification', '0002_initial'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_party_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='classification.party')),
            ],
        ),
        migrations.CreateModel(
            name='DraftSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='quick_add.draft')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_splits_out', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_splits_in', to='accounts.account')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='QuickAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('draft', 'Draft'), ('failed', 'Failed'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='processing', max_length=16)),
                ('failure_reason', models.TextField(blank=True)),
                ('posted_without_edits', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_add', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='quick_add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='quick_add.quickadd'),
        ),
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=200)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12)),
                ('succeeded', models.BooleanField(default=False)),
                ('quick_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to='quick_add.quickadd')),
            ],
            options={
                'verbose_name': 'AI call',
            },
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(('party__isnull', True), ('new_party_name', ''), _connector='OR'), name='quick_add_draft_one_party', violation_error_message='A Draft has an existing Party or a new Party name, not both.'),
        ),
    ]
