# Generated by Django 6.1.2 on 2026-10-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_include_in_net_worth'),
        ('quick_add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsplit',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_splits_out', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='draftsplit',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_splits_in', to='accounts.account'),
        ),
    ]
