# Generated by Django 6.1.2 on 2026-10-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_initial'),
        ('quick_add', '0002_draft_split_keeps_merged_accounts_as_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='classification.party'),
        ),
    ]
