# Generated by Django 6.1.2 on 2026-10-10 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_add', '0004_drafts_own_their_source_and_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftsplit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
