# Generated by Django 6.1.2 on 2026-10-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_initial'),
        ('quick_add', '0005_draft_split_amount_optional'),
        ('schedules', '0001_initial'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='occurrence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='schedules.occurrence'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('occurrence__isnull', False), ('source', 'schedule')), models.Q(models.Q(('source', 'schedule'), _negated=True), ('occurrence__isnull', True)), _connector='OR'), name='quick_add_draft_occurrence_iff_source', violation_error_message='Only a Draft from a Schedule links to an Occurrence.'),
        ),
    ]
