# Generated by Django 6.1.2 on 2026-10-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('classification', '0002_initial'),
        ('quick_add', '0006_draft_links_its_occurrence'),
        ('schedules', '0002_occurrence_transaction'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='statement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='cards.statement'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='source',
            field=models.CharField(choices=[('quick_add', 'Quick Add'), ('schedule', 'Schedule'), ('manual', 'Manual'), ('statement', 'Statement')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'statement'), ('statement__isnull', False)), models.Q(models.Q(('source', 'statement'), _negated=True), ('statement__isnull', True)), _connector='OR'), name='quick_add_draft_statement_iff_source', violation_error_message='Only a card payment Draft links to a Statement.'),
        ),
    ]
