# Generated by Django 6.1.2 on 2026-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_add', '0006_draft_links_its_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
    ]
