# Generated by Django 6.1.2 on 2026-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_add', '0007_draft_links_its_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
    ]
