# Generated by Django 6.1.2 on 2026-10-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_emi'),
        ('classification', '0002_initial'),
        ('quick_add', '0007_draft_links_its_statement'),
        ('schedules', '0004_subscription'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='card_emi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='cards.cardemi'),
        ),
        migrations.AddField(
            model_name='draft',
            name='installment',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='source',
            field=models.CharField(choices=[('quick_add', 'Quick Add'), ('schedule', 'Schedule'), ('manual', 'Manual'), ('statement', 'Statement'), ('card_emi', 'Card EMI')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('card_emi__isnull', False), ('installment__isnull', False), ('source', 'card_emi')), models.Q(models.Q(('source', 'card_emi'), _negated=True), ('card_emi__isnull', True), ('installment__isnull', True)), _connector='OR'), name='quick_add_draft_card_emi_iff_source', violation_error_message='Only a Card EMI Draft links to a Card EMI installment.'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(fields=('card_emi', 'installment'), name='quick_add_draft_one_per_card_emi_installment'),
        ),
    ]
