# Generated by Django 6.1.2 on 2026-10-10 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_add', '0009_draft_links_its_card_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickadd',
            name='processing_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
