# Generated by Django 6.1.2 on 2026-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_emi'),
        ('classification', '0002_initial'),
        ('quick_add', '0010_quick_add_processing_since'),
        ('schedules', '0005_repeat_end_and_auto_post'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['status'], name='quick_add_d_status_0d82a6_idx'),
        ),
    ]
