# Generated by Django 6.1.2 on 2026-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_add', '0011_draft_status_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='processing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
