# Generated by Django 6.1.2 on 2026-10-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('classification', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsplit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsplit',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalsplit_tags',
            name='history',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.historicalsplit'),
        ),
        migrations.AddField(
            model_name='historicalsplit_tags',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classification.tag'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classification.party'),
        ),
        migrations.AddField(
            model_name='split',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits_out', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='split',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='splits', to='classification.tag'),
        ),
        migrations.AddField(
            model_name='split',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits_in', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='historicalsplit_tags',
            name='split',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.split'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='classification.party'),
        ),
        migrations.AddField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='historicalsplit',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.transaction'),
        ),
        migrations.AddConstraint(
            model_name='split',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transactions_split_amount_positive', violation_error_message='Amount must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='split',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='transactions_split_accounts_differ', violation_error_message='A Split cannot go from an Account to itself.'),
        ),
    ]
