# Generated by Django 6.1.2 on 2026-10-09 06:59

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='splits', to='classification.tag'),
        ),
        migrations.CreateModel(
            name='HistoricalSplit_tags',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.historicalsplit')),
                ('split', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.split')),
                ('tag', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classification.tag')),
            ],
            options={
                'verbose_name': 'HistoricalSplit_tags',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
