# Generated by Django 6.1.2 on 2026-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='number_format',
            field=models.CharField(choices=[('indian', 'Indian (₹12,34,567.89)'), ('international', 'International (₹1,234,567.89)')], default='indian', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='number_format',
            field=models.CharField(choices=[('indian', 'Indian (₹12,34,567.89)'), ('international', 'International (₹1,234,567.89)')], default='indian', max_length=13),
        ),
    ]
