# Generated by Django 6.1.2 on 2026-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_number_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_mode',
            field=models.BooleanField(default=False),
        ),
    ]
