# Generated by Django 6.1.2 on 2026-10-10 08:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_account_card_settings'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='From the real statement; leave blank to use the estimate.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.account')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement', to='transactions.transaction')),
            ],
            options={
                'ordering': ('period_end', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('card', 'period_end'), name='cards_statement_one_per_period')],
            },
        ),
    ]
