# Generated by Django 6.1.2 on 2026-10-10 08:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_card_settings'),
        ('cards', '0001_initial'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annual_rate', models.DecimalField(decimal_places=2, help_text='0 for a no-cost EMI.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Annual interest rate (%)')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('first_statement', models.DateField(verbose_name='First billed Statement')),
                ('foreclosed_on', models.DateField(blank=True, null=True)),
                ('foreclosure_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_emis', to='accounts.account')),
                ('interest_account', models.ForeignKey(limit_choices_to={'kind': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='card_emi_interest', to='accounts.account', verbose_name='Interest Expense Account')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_emi', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Card EMI',
                'ordering': ('first_statement', 'pk'),
            },
        ),
    ]
