#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Values land in a separate file per environment, not .env, so the human can
# paste them over the CLOUDFLARE_* lines in their own .env.

TOTAL_STAGES=4

# _dotenv KEY: KEY's value in the project .env, used only for defaults.
_dotenv() { grep -E "^${1}=" .env 2>/dev/null | tail -n1 | cut -d= -f2-; }

banner "Cloudflare analytics setup for the Storage page"

stage "Choose environment"
say "Analytics tokens are read-only, but each environment still gets its own."
WIZARD_ENV=""
until [[ "$WIZARD_ENV" == dev || "$WIZARD_ENV" == prod ]]; do
  printf '  %sSet up dev or prod?%s ' "$BOLD" "$RESET"
  read -r WIZARD_ENV || true
done
ENV_FILE=".env.cloudflare-$WIZARD_ENV"
if [[ "$WIZARD_ENV" == dev ]]; then
  DEFAULT_BUCKET=$(_dotenv R2_BUCKET_NAME); DEFAULT_BUCKET="${DEFAULT_BUCKET:-velora-test}"
else
  DEFAULT_BUCKET=velora
fi
note "Output file: $ENV_FILE (overwritten at the end)"
pause

stage "Copy the account ID"
# The R2 endpoint already embeds the account ID: https://<ACCOUNT_ID>.r2.cloudflarestorage.com
DEFAULT_ACCOUNT=$(_dotenv R2_ENDPOINT_URL | sed -nE 's#^https://([0-9a-f]{32})\..*#\1#p')
if [[ -n "$DEFAULT_ACCOUNT" ]]; then
  note "Found in R2_ENDPOINT_URL in .env: $DEFAULT_ACCOUNT"
else
  open_url "https://dash.cloudflare.com/?to=/:account/r2"
  step "On the R2 overview, find Account Details → Account ID → copy."
fi
CLOUDFLARE_ACCOUNT_ID=""
until [[ "$CLOUDFLARE_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]]; do
  ask CLOUDFLARE_ACCOUNT_ID "Account ID${DEFAULT_ACCOUNT:+ [$DEFAULT_ACCOUNT]}:"
  CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-$DEFAULT_ACCOUNT}"
done

stage "Create an analytics API token"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click Create Token → Create Custom Token → Get started."
step "Token name: velora-analytics-$WIZARD_ENV"
step "Permissions: Account → Account Analytics → Read. Nothing else."
step "Account Resources: Include → the account that owns the R2 bucket."
step "Leave Client IP filtering and TTL empty. Continue to summary → Create Token."
warn "The token is shown only once: keep this page open until it's pasted."
CLOUDFLARE_API_TOKEN=""
until [[ -n "$CLOUDFLARE_API_TOKEN" ]]; do
  ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (hidden):"
done

stage "Save and check"
printf '# Cloudflare analytics settings for %s, from scripts/cloudflare-analytics-setup.sh.\n# Paste over the CLOUDFLARE_* lines in .env, then delete this file.\n' \
  "$WIZARD_ENV" > "$ENV_FILE"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
chmod 600 "$ENV_FILE"

if confirm "Query yesterday's storage for a bucket to check the token?"; then
  CHECK_BUCKET=""
  ask CHECK_BUCKET "Bucket name [$DEFAULT_BUCKET]:"
  CHECK_BUCKET="${CHECK_BUCKET:-$DEFAULT_BUCKET}"
  if CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
     CHECK_BUCKET="$CHECK_BUCKET" python3 -I - <<'PY'
import json, os, urllib.error, urllib.request
from datetime import UTC, datetime, timedelta

end = datetime.now(UTC)
query = """
query ($accountTag: string!, $bucketName: string, $start: Time, $end: Time) {
  viewer { accounts(filter: { accountTag: $accountTag }) {
    r2StorageAdaptiveGroups(limit: 1, filter: { bucketName: $bucketName, datetime_geq: $start, datetime_leq: $end }) {
      max { payloadSize objectCount }
    }
  } }
}
"""
variables = {
    "accountTag": os.environ["CLOUDFLARE_ACCOUNT_ID"],
    "bucketName": os.environ["CHECK_BUCKET"],
    "start": (end - timedelta(days=1)).isoformat(timespec="seconds"),
    "end": end.isoformat(timespec="seconds"),
}
request = urllib.request.Request(
    "https://api.cloudflare.com/client/v4/graphql",
    data=json.dumps({"query": query, "variables": variables}).encode(),
    headers={
        "Authorization": f"Bearer {os.environ['CLOUDFLARE_API_TOKEN']}",
        "Content-Type": "application/json",
    },
)
try:
    with urllib.request.urlopen(request, timeout=10) as response:
        data = json.load(response)
except urllib.error.HTTPError as error:
    raise SystemExit(f"Cloudflare said {error.code}: {error.read().decode()[:500]}") from None
if data.get("errors"):
    raise SystemExit(f"Cloudflare said: {data['errors']}")
accounts = data["data"]["viewer"]["accounts"]
if not accounts:
    raise SystemExit("No account matched: check the account ID and the token's Account Resources.")
groups = accounts[0]["r2StorageAdaptiveGroups"]
print(f"  {groups[0]['max'] if groups else 'no data yet for this bucket (fine for a new or empty one)'}")
PY
  then
    printf '  %s✓ token can read R2 analytics for %s%s\n' "$GREEN" "$CHECK_BUCKET" "$RESET"
  else
    SKIPPED+=("Analytics check failed: fix the values in $ENV_FILE and re-run")
    warn "check failed: see the error above"
  fi
  pause
fi

finish
note "Next: paste $ENV_FILE over the CLOUDFLARE_* lines in your $WIZARD_ENV .env, then delete it."
printf '\n'
