#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Values land in a separate file per environment, not .env, so the human can
# paste them over the commented R2_* block in their own .env.

TOTAL_STAGES=6
DASH="https://dash.cloudflare.com/?to=/:account/r2"

banner "Cloudflare R2 setup for Attachments"

stage "Choose environment"
say "Each environment gets its own bucket and its own API token."
say "Dev uses a separate test bucket, never the production one."
WIZARD_ENV=""
until [[ "$WIZARD_ENV" == dev || "$WIZARD_ENV" == prod ]]; do
  printf '  %sSet up dev or prod?%s ' "$BOLD" "$RESET"
  read -r WIZARD_ENV || true
done
ENV_FILE=".env.r2-$WIZARD_ENV"
if [[ "$WIZARD_ENV" == dev ]]; then DEFAULT_BUCKET=velora-test; else DEFAULT_BUCKET=velora; fi
note "Output file: $ENV_FILE (overwritten at the end)"
pause

stage "Create the bucket"
open_url "$DASH/new"
step "If R2 isn't enabled on the account yet, accept the R2 plan first."
step "Bucket name: $DEFAULT_BUCKET (or your own)."
step "Location: Automatic. Default storage class: Standard."
step "Click Create bucket."
R2_BUCKET_NAME=""
while [[ -z "$R2_BUCKET_NAME" ]]; do
  ask R2_BUCKET_NAME "Bucket name you created [$DEFAULT_BUCKET]:"
  R2_BUCKET_NAME="${R2_BUCKET_NAME:-$DEFAULT_BUCKET}"
done

stage "Keep the bucket private"
say "Receipts are sensitive: objects must only be reachable via presigned links."
step "Open bucket $R2_BUCKET_NAME → Settings."
step "Public Development URL (r2.dev): must say Disabled."
step "Custom Domains: must be empty."
step "Leave CORS empty: uploads go through Django, not the browser."
until confirm "Both public access options are off?"; do
  warn "Turn off the r2.dev URL and remove any custom domain first."
done

stage "Create an API token"
open_url "$DASH/api-tokens"
step "Click Create Account API token."
step "Name: velora-$WIZARD_ENV"
step "Permissions: Object Read & Write."
step "Specify bucket(s): Apply to specific buckets only → $R2_BUCKET_NAME."
step "TTL: Forever. Click Create Account API Token."
warn "The secret is shown only once: keep this page open until the end."
pause "Press Enter when the token page shows the keys"

stage "Copy the token values"
R2_ACCESS_KEY_ID=""
until [[ "$R2_ACCESS_KEY_ID" =~ ^[0-9a-f]{32}$ ]]; do
  ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
done
R2_SECRET_ACCESS_KEY=""
until [[ "$R2_SECRET_ACCESS_KEY" =~ ^[0-9a-f]{64}$ ]]; do
  ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key (hidden):"
done
step "Copy the default S3 endpoint: https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
R2_ENDPOINT_URL=""
until [[ "$R2_ENDPOINT_URL" =~ ^https://[0-9a-f]{32}(\.[a-z]+)?\.r2\.cloudflarestorage\.com$ ]]; do
  ask R2_ENDPOINT_URL "Paste the endpoint URL:"
  R2_ENDPOINT_URL="${R2_ENDPOINT_URL%/}"
done

stage "Save and check"
printf '# R2 settings for %s, from scripts/r2-setup.sh.\n# Paste over the R2_* lines in .env, then delete this file.\n' \
  "$WIZARD_ENV" > "$ENV_FILE"
write_env R2_ENDPOINT_URL "$R2_ENDPOINT_URL"
write_env R2_BUCKET_NAME "$R2_BUCKET_NAME"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
chmod 600 "$ENV_FILE"

if confirm "Upload, read and delete a test object to check the token?"; then
  if R2_ENDPOINT_URL="$R2_ENDPOINT_URL" R2_BUCKET_NAME="$R2_BUCKET_NAME" \
     R2_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" R2_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" \
     uv run --quiet python - <<'PY'
import os, uuid
import boto3

s3 = boto3.client(
    "s3",
    endpoint_url=os.environ["R2_ENDPOINT_URL"],
    aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
    region_name="auto",
)
bucket, key = os.environ["R2_BUCKET_NAME"], f"wizard-check-{uuid.uuid4().hex}"
s3.put_object(Bucket=bucket, Key=key, Body=b"ok")
assert s3.get_object(Bucket=bucket, Key=key)["Body"].read() == b"ok"
s3.delete_object(Bucket=bucket, Key=key)
PY
  then
    printf '  %s✓ token can read, write and delete in %s%s\n' "$GREEN" "$R2_BUCKET_NAME" "$RESET"
  else
    SKIPPED+=("R2 check failed: fix the values in $ENV_FILE and re-run")
    warn "check failed: see the error above"
  fi
  pause
fi

finish
note "Next: paste $ENV_FILE over the R2_* lines in your $WIZARD_ENV .env, then delete it."
printf '\n'
