# Generated by Django 6.1.2 on 2026-10-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(unique=True)),
            ],
            options={
                'ordering': ('sent_on',),
            },
        ),
    ]
