# Generated by Django 6.1.2 on 2026-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='how_to_cancel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='trial_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='how_to_cancel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='trial_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
