# Generated by Django 6.1.2 on 2026-10-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence', to='transactions.transaction'),
        ),
    ]
