# Generated by Django 6.1.2 on 2026-10-10 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_include_in_net_worth'),
        ('classification', '0002_initial'),
        ('schedules', '0002_occurrence_transaction'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='waiting', max_length=16)),
                ('evidence', models.ManyToManyField(related_name='suggested_schedules', to='transactions.transaction')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_schedules_out', to='accounts.account')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_schedules', to='classification.party')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_schedules_in', to='accounts.account')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
