# Generated by Django 6.1.2 on 2026-10-10 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_initial'),
        ('schedules', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='cron',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='ends_after',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cron',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ends_after',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='every',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='every',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='unit',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cron', ''), ('every__isnull', False), models.Q(('unit', ''), _negated=True)), models.Q(models.Q(('cron', ''), _negated=True), ('every__isnull', True), ('unit', '')), _connector='OR'), name='schedules_schedule_interval_or_cron', violation_error_message='A Schedule repeats on an interval or a cron expression, not both.'),
        ),
    ]
