# Generated by Django 6.1.2 on 2026-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_low_balance_threshold'),
        ('classification', '0002_initial'),
        ('schedules', '0005_repeat_end_and_auto_post'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suggestedschedule',
            index=models.Index(fields=['status'], name='schedules_s_status_003bd7_idx'),
        ),
    ]
