# Generated by Django 6.1.2 on 2026-10-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_suggested_schedule_status_indexed'),
        ('transactions', '0003_attachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['status', 'due_date'], name='schedules_o_status_03bbce_idx'),
        ),
    ]
