# Generated by Django 6.1.2 on 2026-10-08 09:06

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='tag', max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16)),
                ('hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical category',
                'verbose_name_plural': 'historical categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExpenseAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense account',
                'verbose_name_plural': 'historical expense accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='tag', max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('kind'), name='budget_category_kind_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'expense accounts',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='budget_expenseaccount_name_ci_unique')],
            },
        ),
    ]
