# Generated by Django 6.1.2 on 2026-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcategorygroup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
