# Generated by Django 6.1.2 on 2026-10-08 07:52

from django.db import migrations, models


REMAP = {
    "lime": "green",
    "emerald": "green",
    "teal": "cyan",
    "sky": "cyan",
    "fuchsia": "pink",
    "rose": "pink",
}


def remap_colors(apps, schema_editor):
    for model_name in ("Category", "HistoricalCategory"):
        model = apps.get_model("budget", model_name)
        for old, new in REMAP.items():
            model.objects.filter(color=old).update(color=new)


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_hidden'),
    ]

    operations = [
        migrations.RunPython(remap_colors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='color',
            field=models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16),
        ),
    ]
