# Generated by Django 6.1.2 on 2026-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='color',
            field=models.CharField(choices=[('slate', 'Slate'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('violet', 'Violet'), ('pink', 'Pink')], max_length=16),
        ),
    ]
