# Generated by Django 6.1.2 on 2026-10-08 08:00

import apps.budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_palette_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=apps.budget.models._protect_unless_owner_deleted, related_name='categories', to='budget.categorygroup'),
        ),
    ]
